### ISSUE TITLE
Missing package for ansible install

### ISSUE THREAD

**Issue by Orsolino** [belminf/belminf.github.io#6]
Hi,
I've got problem with installing ansible in babun shell like:
"error: command 'gcc' failed with exit status 1"

Solution is described here [https://github.com/babun/babun/blob/master/babun-doc/adoc/_faq.adoc#46-i-see-error-command-gcc-failed-with-exit-status-1](url)

What do you think about to add libffi-devel package in requirements in your [article ](http://iambelmin.com/2016/01/01/installing-ansible-on-babun/)?

**Comment by belminf** [comment]
Thanks for the heads up!
